*Q1*
# Find first and second principal components. Explain your solution step by step.

In [17]:
import numpy as np
import pandas as pd
# inputting the matrix x1 x2 - inserting the data set
A = np.matrix([[2.2,2.1],
               [0.4,0.6],
               [1.6,2.3],
               [2,2.1],
               [2.9,2.8],
               [0.8,1.1],
               [1.3,1.4],
               [1.1,1],
               [2.3,2.6]])

dataf = pd.DataFrame(A,columns = ['x1','x2'])
dataf

# standardize the dataset
df_standardized = (dataf - dataf.mean()) / (dataf.std())
df_standardized

# find the covariance (population) matrix for the given data set
dataf_cov = np.cov(df_standardized.T,bias = 1)
dataf_cov

# verify var(x1) 
print('var(f1) (population formula): ',((df_standardized.x1)**2).sum()/9)

# verify cov(x1,x2)
print('cov(f1,f2) (population formula): ',((df_standardized.x1)*(df_standardized.x2)).sum()/9)

# calculate evalue and evector
eigen_val, eigen_vectors = np.linalg.eig(dataf_cov)
print("Eig-val:\n",eigen_val)
print("Eig-vec:\n",eigen_vectors)

# sort the e values and corresponding e vectors
number_of_components = 2
top_eigen_vectors = eigen_vectors[:,:number_of_components]
top_eigen_vectors.shape
np.array(df_standardized).shape
transformed_data = np.matmul(np.array(df_standardized),top_eigen_vectors)
pd.DataFrame(data = transformed_data
             , columns = ['Principal component '+ str(i+1) for i in range(number_of_components)])
transformed_data.shape

# using PCA in sklearn
from sklearn.decomposition import PCA
# define number of components
pca = PCA(n_components=number_of_components)
# transform standardized data set
principalComponents = pca.fit_transform(df_standardized)
# define the pricipal components data frame
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['Principal Component '+ str(i+1) for i in range(number_of_components)])
# print the principal components data frame
principalDf

var(f1) (population formula):  0.8888888888888888
cov(f1,f2) (population formula):  0.8406973999676008
Eig-val:
 [0.04819149 1.72958629]
Eig-vec:
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


Principal Component 1  Principal Component 2
0              -0.805194              -0.216626
1               2.156428               0.005114
2              -0.457292               0.496593
3              -0.628340              -0.039773
4              -2.063486              -0.196308
5               1.346075               0.108054
6               0.629953              -0.060092
7               1.172124              -0.248556
8              -1.350267               0.151594

*Q2*
# Write a Python script that calculates approximations of an image using Singular Value Decomposition.

In [18]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

In [19]:
# import image as image.jpg
img = cv2.imread('image.jpg',0)

In [20]:
from numpy.linalg import svd

In [21]:
# k = 1,5,10,20,40
# create a methof to approximate image with various values for k
def approxi(img,k):
  U,s,V = svd(img,full_matrices = False)
  reconstructedMatrix = np.dot(U[:,:k],np.dot(np.diag(s[:k]),V[:k,:]))
  return reconstructedMatrix,s

In [22]:
# k = 1
print("k=1")
mat1 = approxi(img,1)
print(mat1)

# k = 5
print("k=5")
mat5 = approxi(img,5)
print(mat5)

# k = 10
print("k=10")
mat10 = approxi(img,10)
print(mat10)

# k = 20 
print("k=20")
mat20 = approxi(img,20)
print(mat20)

# k = 40
print("k=40")
mat40 = approxi(img,40)
print(mat40)

k=1
(array([[130.54694578, 130.52334332, 130.4866951 , ..., 148.63801859,
        148.74064025, 148.79681094],
       [129.84933685, 129.82586052, 129.78940814, ..., 147.84373568,
        147.94580895, 148.00167948],
       [129.03187082, 129.00854229, 128.97231939, ..., 146.91298597,
        147.01441665, 147.06993544],
       ...,
       [ 88.79643627,  88.78038217,  88.7554545 , ..., 101.1017628 ,
        101.17156479, 101.20977141],
       [ 88.89111944,  88.87504822,  88.85009397, ..., 101.20956707,
        101.2794435 , 101.31769086],
       [ 89.27026816,  89.25412839,  89.2290677 , ..., 101.64125786,
        101.71143233, 101.74984282]]), array([1.96358642e+05, 3.82897607e+04, 3.64077538e+04, ...,
       5.37743999e+00, 5.29537110e+00, 5.11965639e+00]))
k=5
(array([[194.05357278, 194.17709664, 194.22441528, ...,  55.56134614,
         55.69143123,  55.85680958],
       [194.23151582, 194.35247381, 194.3993644 , ...,  55.2900777 ,
         55.42310729,  55.58840207],
       [193